name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies (Root)
      run: npm ci
    
    - name: Install dependencies (Bot)
      run: |
        cd bot-whatsapp
        npm ci
    
    - name: Create environment file
      run: |
        cd bot-whatsapp
        cp .env.example .env
    
    - name: Initialize database
      run: |
        cd bot-whatsapp
        node init-db.js
    
    - name: Run linting
      run: npm run lint
      continue-on-error: true
    
    - name: Build Next.js application
      run: npm run build
    
    - name: Test API endpoints
      run: |
        npm start &
        sleep 10
        curl -f http://localhost:3000/api/orders || exit 1
        pkill -f "npm start"

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Run security audit
      run: |
        npm audit --audit-level moderate
        cd bot-whatsapp
        npm audit --audit-level moderate
      continue-on-error: true

  deploy:
    needs: [test, security]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy notification
      run: echo "Ready for deployment to production"
